# Generated by Django 2.2 on 2019-05-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('draft', models.BooleanField(default=True)),
            ],
        ),
    ]
