# Generated by Django 2.2 on 2019-05-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190505_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='hero/')),
                ('caption', models.CharField(max_length=250)),
                ('sub_heading', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
