# Generated by Django 2.2 on 2019-05-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_story_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
